#include "geodesic.hpp"

#include "metric.hpp"

// Kerr geodesics in Hamiltonian form (THEORY.md, "Geodesic equations
// (Hamiltonian form)"). The inverse-metric components and their r/theta
// derivatives come from kerr_terms(), generated by matlab/derive_kerr.m.

namespace bhsim {

KerrState kerr_rhs(const KerrState& y, const Kerr& bh) {
    const double r  = y[KR];
    const double th = y[KTH];
    const double pt = y[KPT], pr = y[KPR], pth = y[KPTH], pph = y[KPPH];

    const KerrTerms k = kerr_terms(r, th, bh.a, bh.M);

    // dx^mu/dlambda = g^{mu nu} p_nu   (only t, r, theta, phi couplings)
    KerrState dy{};
    dy[KT]   = k.gtt * pt + k.gtph * pph;
    dy[KR]   = k.grr * pr;
    dy[KTH]  = k.gthth * pth;
    dy[KPHI] = k.gtph * pt + k.gphph * pph;

    // dp_mu/dlambda = -1/2 (d_mu g^{ab}) p_a p_b, for mu = r, theta.
    // p_t and p_phi are conserved (metric has no t/phi dependence), so their
    // derivatives stay zero.
    const auto quad = [&](double a_tt, double a_tph, double a_phph,
                          double a_rr, double a_thth) {
        return a_tt * pt * pt + 2.0 * a_tph * pt * pph + a_phph * pph * pph
             + a_rr * pr * pr + a_thth * pth * pth;
    };
    dy[KPR]  = -0.5 * quad(k.d_r_gtt,  k.d_r_gtph,  k.d_r_gphph,  k.d_r_grr,  k.d_r_gthth);
    dy[KPTH] = -0.5 * quad(k.d_th_gtt, k.d_th_gtph, k.d_th_gphph, k.d_th_grr, k.d_th_gthth);
    // dy[KPT] = 0, dy[KPPH] = 0

    return dy;
}

}  // namespace bhsim
