#include "geodesic.hpp"

#include <cmath>

#include "integrator.hpp"
#include "metric.hpp"

// Kerr geodesics in Hamiltonian form (THEORY.md, "Geodesic equations
// (Hamiltonian form)"). The inverse-metric components and their r/theta
// derivatives come from kerr_terms(), generated by matlab/derive_kerr.m.

namespace bhsim {

KerrState kerr_rhs(const KerrState& y, const Kerr& bh) {
    const double r  = y[KR];
    const double th = y[KTH];
    const double pt = y[KPT], pr = y[KPR], pth = y[KPTH], pph = y[KPPH];

    const KerrTerms k = kerr_terms(r, th, bh.a, bh.M);

    // dx^mu/dlambda = g^{mu nu} p_nu   (only t, r, theta, phi couplings)
    KerrState dy{};
    dy[KT]   = k.gtt * pt + k.gtph * pph;
    dy[KR]   = k.grr * pr;
    dy[KTH]  = k.gthth * pth;
    dy[KPHI] = k.gtph * pt + k.gphph * pph;

    // dp_mu/dlambda = -1/2 (d_mu g^{ab}) p_a p_b, for mu = r, theta.
    // p_t and p_phi are conserved (metric has no t/phi dependence), so their
    // derivatives stay zero.
    const auto quad = [&](double a_tt, double a_tph, double a_phph,
                          double a_rr, double a_thth) {
        return a_tt * pt * pt + 2.0 * a_tph * pt * pph + a_phph * pph * pph
             + a_rr * pr * pr + a_thth * pth * pth;
    };
    dy[KPR]  = -0.5 * quad(k.d_r_gtt,  k.d_r_gtph,  k.d_r_gphph,  k.d_r_grr,  k.d_r_gthth);
    dy[KPTH] = -0.5 * quad(k.d_th_gtt, k.d_th_gtph, k.d_th_gphph, k.d_th_grr, k.d_th_gthth);
    // dy[KPT] = 0, dy[KPPH] = 0

    return dy;
}

// Equatorial photon (theta = pi/2, p_theta = 0), inward, from the H = 0
// constraint g^{ab} p_a p_b = 0 solved for p_r.
KerrState kerr_equatorial_photon(const Kerr& bh, double r0, double b) {
    const double PI = std::acos(-1.0);
    KerrState y{};
    y[KT] = 0.0; y[KR] = r0; y[KTH] = PI / 2; y[KPHI] = 0.0;
    y[KPT] = -1.0; y[KPPH] = b; y[KPTH] = 0.0;

    const KerrTerms k = kerr_terms(r0, PI / 2, bh.a, bh.M);
    const double pt = y[KPT], pph = y[KPPH];
    const double pr2 = -(k.gtt * pt * pt + 2.0 * k.gtph * pt * pph + k.gphph * pph * pph) / k.grr;
    y[KPR] = -std::sqrt(pr2 > 0.0 ? pr2 : 0.0);
    return y;
}

std::vector<Row> trace_kerr(const Kerr& bh, KerrState y, double r_escape,
                            double lambda_max, std::string& outcome,
                            double atol, double rtol, long max_steps) {
    const auto rhs = [&](const KerrState& s) { return kerr_rhs(s, bh); };
    const double r_capture = 1.01 * bh.horizon();

    std::vector<Row> rows;
    auto push = [&](double lam, const KerrState& s) {
        rows.push_back({lam, s[KR], s[KPHI], s[KR] * std::cos(s[KPHI]), s[KR] * std::sin(s[KPHI])});
    };

    double lambda = 0.0, h = 0.1;
    push(lambda, y);
    outcome = "max steps reached";

    for (long i = 0; i < max_steps; ++i) {
        lambda += adaptive_step<8>(y, h, rhs, atol, rtol);
        push(lambda, y);
        if (y[KR] <= r_capture)                 { outcome = "captured";  break; }
        if (y[KPR] > 0.0 && y[KR] >= r_escape)  { outcome = "escaped";   break; }
        if (lambda >= lambda_max)               { outcome = "max lambda"; break; }
    }
    return rows;
}

}  // namespace bhsim
