% derive_kerr.m
% ---------------------------------------------------------------------------
% Symbolically derive the Kerr inverse-metric components (Boyer-Lindquist) and
% their r/theta derivatives, export them as a C++ header, and generate an
% ode113 reference trajectory as a test fixture.
%
% Requires the Symbolic Math Toolbox. Paths resolve relative to this script,
% so it can be run from any current folder:
%     matlab -batch "run('matlab/derive_kerr.m')"
% (or open in the MATLAB editor and press Run).
% ---------------------------------------------------------------------------

clear; clc;
syms r th a M real

% Resolve output paths relative to THIS script, not the current folder.
this_dir = fileparts(mfilename('fullpath'));
if isempty(this_dir); this_dir = pwd; end
repo    = fileparts(this_dir);
inc_dir = fullfile(repo, 'include');
fix_dir = fullfile(repo, 'tests', 'fixtures');
if ~exist(inc_dir, 'dir'); mkdir(inc_dir); end
if ~exist(fix_dir, 'dir'); mkdir(fix_dir); end

Sigma = r^2 + a^2*cos(th)^2;
Delta = r^2 - 2*M*r + a^2;
s2    = sin(th)^2;

% Nonzero inverse-metric components (contravariant), Boyer-Lindquist.
gtt   = -((r^2 + a^2)^2 - a^2*Delta*s2)/(Sigma*Delta);
gtph  = -(2*M*a*r)/(Sigma*Delta);
gphph = (Delta - a^2*s2)/(Sigma*Delta*s2);
grr   = Delta/Sigma;
gthth = 1/Sigma;

comps = [gtt, gtph, gphph, grr, gthth];
names = ["gtt", "gtph", "gphph", "grr", "gthth"];

dr  = simplify(diff(comps, r));
dth = simplify(diff(comps, th));

% ---- write the C++ header -------------------------------------------------
hdr = fullfile(inc_dir, 'kerr_generated.hpp');
fid = fopen(hdr, 'w');
if fid < 0; error('could not open %s for writing', hdr); end
fprintf(fid, '#pragma once\n');
fprintf(fid, '// AUTO-GENERATED by matlab/derive_kerr.m -- do not edit by hand.\n');
fprintf(fid, '// Kerr inverse-metric components and r/theta derivatives (Boyer-Lindquist).\n');
fprintf(fid, '#include <cmath>\n\nnamespace bhsim {\n\n');
fprintf(fid, 'struct KerrTerms {\n');
for n = names
    fprintf(fid, '    double %s, d_r_%s, d_th_%s;\n', n, n, n);
end
fprintf(fid, '};\n\n');
fprintf(fid, 'inline KerrTerms kerr_terms(double r, double th, double a, double M) {\n');
fprintf(fid, '    using std::sin; using std::cos; using std::pow; using std::sqrt;\n');
fprintf(fid, '    KerrTerms k;\n');
for i = 1:numel(names)
    emit_block(fid, sprintf('k.%s',      names(i)), comps(i));
    emit_block(fid, sprintf('k.d_r_%s',  names(i)), dr(i));
    emit_block(fid, sprintf('k.d_th_%s', names(i)), dth(i));
end
fprintf(fid, '    return k;\n}\n\n');
fprintf(fid, '}  // namespace bhsim\n');
fclose(fid);
fprintf('wrote %s\n', hdr);

% ---- numeric RHS + reference trajectory -----------------------------------
gfun   = matlabFunction(comps.', 'Vars', {r, th, a, M});
drfun  = matlabFunction(dr.',    'Vars', {r, th, a, M});
dthfun = matlabFunction(dth.',   'Vars', {r, th, a, M});

a_val = 0.5;  M_val = 1.0;
% state y = [t, r, th, phi, p_t, p_r, p_th, p_phi]
y0 = [0; 10; 1.2; 0;  -0.97; 0.0; 0.4; 3.5];
lam_end = 80;

rplus = M_val + sqrt(M_val^2 - a_val^2);
opts = odeset('RelTol', 1e-11, 'AbsTol', 1e-12, ...
              'Events', @(lam, y) horizon_event(y, rplus));
rhs = @(lam, y) kerr_rhs(y, a_val, M_val, gfun, drfun, dthfun);

[lam, Y] = ode113(rhs, linspace(0, lam_end, 801), y0, opts);

fix = fullfile(fix_dir, 'kerr_ref_a05.csv');
fout = fopen(fix, 'w');
if fout < 0; error('could not open %s for writing', fix); end
fprintf(fout, '# a=%.3f M=%.3f  columns: lambda,t,r,th,phi,pt,pr,pth,pphi\n', a_val, M_val);
fprintf(fout, 'lambda,t,r,th,phi,pt,pr,pth,pphi\n');
for i = 1:numel(lam)
    fprintf(fout, '%.10f,%.10f,%.10f,%.10f,%.10f,%.10f,%.10f,%.10f,%.10f\n', ...
            lam(i), Y(i,1), Y(i,2), Y(i,3), Y(i,4), Y(i,5), Y(i,6), Y(i,7), Y(i,8));
end
fclose(fout);
fprintf('wrote %s  (%d points, final r = %.4f)\n', fix, numel(lam), Y(end,2));

% ===========================================================================
% local functions
% ===========================================================================
function emit_block(fid, lhs, expr)
    % Emit `<lhs> = <expr>;` as a scoped C++ block, declaring ccode temporaries.
    code  = ccode(expr);
    lines = splitlines(string(code));
    lines = lines(strlength(strip(lines)) > 0);
    fprintf(fid, '    {\n');
    result_var = "";
    for i = 1:numel(lines)
        ln  = strip(lines(i));
        tok = regexp(ln, '^([A-Za-z_]\w*)\s*=', 'tokens', 'once');
        if ~isempty(tok)
            result_var = string(tok{1});
            fprintf(fid, '        double %s\n', ln);  % declare temp/result
        else
            fprintf(fid, '        %s\n', ln);
        end
    end
    fprintf(fid, '        %s = %s;\n', lhs, result_var);
    fprintf(fid, '    }\n');
end

function dy = kerr_rhs(y, a, M, gfun, drfun, dthfun)
    r = y(2); th = y(3);
    pt = y(5); pr = y(6); pth = y(7); pph = y(8);
    g   = gfun(r, th, a, M);    % [gtt; gtph; gphph; grr; gthth]
    dgr = drfun(r, th, a, M);
    dgt = dthfun(r, th, a, M);
    gtt = g(1); gtph = g(2); gphph = g(3); grr = g(4); gthth = g(5);

    dy = zeros(8, 1);
    dy(1) = gtt*pt + gtph*pph;    % dt/dlam
    dy(2) = grr*pr;               % dr/dlam
    dy(3) = gthth*pth;            % dth/dlam
    dy(4) = gtph*pt + gphph*pph;  % dphi/dlam
    quad = @(D) D(1)*pt^2 + 2*D(2)*pt*pph + D(3)*pph^2 + D(4)*pr^2 + D(5)*pth^2;
    dy(6) = -0.5*quad(dgr);       % dp_r/dlam
    dy(7) = -0.5*quad(dgt);       % dp_th/dlam
    % dy(5) = dp_t = 0, dy(8) = dp_phi = 0  (E and L_z conserved)
end

function [value, isterminal, direction] = horizon_event(y, rplus)
    value = y(2) - 1.05*rplus;   % stop just outside the outer horizon
    isterminal = 1;
    direction = -1;
end
