#pragma once
// AUTO-GENERATED by matlab/derive_kerr.m -- do not edit by hand.
// Kerr inverse-metric components and r/theta derivatives (Boyer-Lindquist).
#include <cmath>

namespace bhsim {

struct KerrTerms {
    double gtt, d_r_gtt, d_th_gtt;
    double gtph, d_r_gtph, d_th_gtph;
    double gphph, d_r_gphph, d_th_gphph;
    double grr, d_r_grr, d_th_grr;
    double gthth, d_r_gthth, d_th_gthth;
};

inline KerrTerms kerr_terms(double r, double th, double a, double M) {
    using std::sin; using std::cos; using std::pow; using std::sqrt;
    KerrTerms k;
    {
        double t0 = -(pow(a*a+r*r,2.0)-(a*a)*pow(sin(th),2.0)*(M*r*-2.0+a*a+r*r))/(((a*a)*pow(cos(th),2.0)+r*r)*(M*r*-2.0+a*a+r*r));
        k.gtt = t0;
    }
    {
        double t0 = -(r*(a*a+r*r)*4.0+(a*a)*pow(sin(th),2.0)*(M*2.0-r*2.0))/(((a*a)*pow(cos(th),2.0)+r*r)*(M*r*-2.0+a*a+r*r))+(r*(pow(a*a+r*r,2.0)-(a*a)*pow(sin(th),2.0)*(M*r*-2.0+a*a+r*r))*1.0/pow((a*a)*pow(cos(th),2.0)+r*r,2.0)*2.0)/(M*r*-2.0+a*a+r*r)-((pow(a*a+r*r,2.0)-(a*a)*pow(sin(th),2.0)*(M*r*-2.0+a*a+r*r))*(M*2.0-r*2.0)*1.0/pow(M*r*-2.0+a*a+r*r,2.0))/((a*a)*pow(cos(th),2.0)+r*r);
        k.d_r_gtt = t0;
    }
    {
        double t0 = ((a*a)*cos(th)*sin(th)*2.0)/((a*a)*pow(cos(th),2.0)+r*r)-((a*a)*cos(th)*sin(th)*(pow(a*a+r*r,2.0)-(a*a)*pow(sin(th),2.0)*(M*r*-2.0+a*a+r*r))*1.0/pow((a*a)*pow(cos(th),2.0)+r*r,2.0)*2.0)/(M*r*-2.0+a*a+r*r);
        k.d_th_gtt = t0;
    }
    {
        double t0 = (M*a*r*-2.0)/(((a*a)*pow(cos(th),2.0)+r*r)*(M*r*-2.0+a*a+r*r));
        k.gtph = t0;
    }
    {
        double t0 = M*a*1.0/pow((a*a)*pow(cos(th),2.0)+r*r,2.0)*1.0/pow(M*r*-2.0+a*a+r*r,2.0)*(-(a*a*a*a)*pow(cos(th),2.0)-M*(r*r*r)*4.0+(r*r*r*r)*3.0+(a*a)*(r*r)+(a*a)*(r*r)*pow(cos(th),2.0))*2.0;
        k.d_r_gtph = t0;
    }
    {
        double t0 = (M*(a*a*a)*r*cos(th)*sin(th)*1.0/pow((a*a)*pow(cos(th),2.0)+r*r,2.0)*-4.0)/(M*r*-2.0+a*a+r*r);
        k.d_th_gtph = t0;
    }
    {
        double t0 = -(1.0/pow(sin(th),2.0)*(M*r*2.0+(a*a)*pow(sin(th),2.0)-a*a-r*r))/(((a*a)*pow(cos(th),2.0)+r*r)*(M*r*-2.0+a*a+r*r));
        k.gphph = t0;
    }
    {
        double t0 = 1.0/pow(sin(th),2.0)*1.0/pow((a*a)*pow(cos(th),2.0)+r*r,2.0)*1.0/pow(M*r*-2.0+a*a+r*r,2.0)*(M*(r*r*r*r)*-4.0+(a*a*a*a)*r+r*r*r*r*r+(M*M)*(r*r*r)*4.0+(a*a)*(r*r*r)*2.0-(a*a)*(r*r*r)*pow(sin(th),2.0)*2.0-M*(a*a)*(r*r)*4.0-(a*a*a*a)*r*pow(sin(th),2.0)-(a*a*a*a)*r*pow(cos(th),2.0)*pow(sin(th),2.0)+M*(a*a)*(r*r)*pow(sin(th),2.0)*3.0+M*(a*a*a*a)*pow(cos(th),2.0)*pow(sin(th),2.0))*-2.0;
        k.d_r_gphph = t0;
    }
    {
        double t0 = (cos(th)*1.0/pow(sin(th),3.0)*1.0/pow((a*a)*pow(cos(th),2.0)+r*r,2.0)*(((a*a*a*a)*cos(th*2.0))/2.0-M*(r*r*r)*2.0+((a*a*a*a)*pow(cos(th*2.0),2.0))/4.0+(a*a*a*a)/4.0+r*r*r*r+(a*a)*(r*r)+(a*a)*(r*r)*cos(th*2.0)-M*(a*a)*r*cos(th*2.0)*2.0)*-2.0)/(M*r*-2.0+a*a+r*r);
        k.d_th_gphph = t0;
    }
    {
        double t0 = (M*r*-2.0+a*a+r*r)/((a*a)*pow(cos(th),2.0)+r*r);
        k.grr = t0;
    }
    {
        double t0 = 1.0/pow((a*a)*pow(cos(th),2.0)+r*r,2.0)*(M*(r*r)-(a*a)*r-M*(a*a)*pow(cos(th),2.0)+(a*a)*r*pow(cos(th),2.0))*2.0;
        k.d_r_grr = t0;
    }
    {
        double t0 = (a*a)*cos(th)*sin(th)*1.0/pow((a*a)*pow(cos(th),2.0)+r*r,2.0)*(M*r*-2.0+a*a+r*r)*2.0;
        k.d_th_grr = t0;
    }
    {
        double t0 = 1.0/((a*a)*pow(cos(th),2.0)+r*r);
        k.gthth = t0;
    }
    {
        double t0 = r*1.0/pow((a*a)*pow(cos(th),2.0)+r*r,2.0)*-2.0;
        k.d_r_gthth = t0;
    }
    {
        double t0 = (a*a)*cos(th)*sin(th)*1.0/pow((a*a)*pow(cos(th),2.0)+r*r,2.0)*2.0;
        k.d_th_gthth = t0;
    }
    return k;
}

}  // namespace bhsim
